# Example of config file

BIND_ADDR = "<SERVER_IP>:<SERVER_PORT>"
LOG_LEVEL = "<LOG_LEVEL>[PANIC,FATAL,ERROR,WARN,INFO,DEBUG,TRACE]"

DATABASE_HOST = "<DATABASE_HOST>"
DATABASE_DB = "<DATABASE_DB>"
DATABASE_USER = "<DATABASE_USER>"
DATABASE_PASSWORD = "<DATABASE_PASSWORD>"
DATABASE_SSLMODE = "<DATABASE_SSLMODE>"